title: Welcome to KC Legal Hackers!
logo: /KCLH-logo-square.png
description: [Legal Hackers](legalhackers.org) is a global movement of lawyers, policymakers, designers, technologists, and academics who explore and develop creative solutions to some of the most pressing issues at the intersection of law and technology. Through local meetups, hackathons, and workshops, Legal Hackers spot issues and opportunities where technology can improve and inform the practice of law and where law, legal practice, and policy can adapt to rapidly changing technology.
theme: jekyll-theme-minimal
